In [2]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

## 교차검증 KFold

In [4]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []

In [6]:
kfold

KFold(n_splits=5, random_state=None, shuffle=False)

In [7]:
n_iter = 0

# KFold 객체의 split()을 호출하면 폴드 별 학습용, 테스트용 데이터의 인덱스를 array로 반환
for traind_idx, test_idx in kfold.split(features):
    X_train, X_test = features[traind_idx], features[test_idx]
    y_train, y_test = label[traind_idx], label[test_idx]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(y_test, pred), 4)
    cv_accuracy.append(accuracy)

    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(f'\n#{n_iter} 교차 검증 정확도 : {accuracy}, 학습 데이터 크기 : {train_size}, 테스트 데이터 크기 : {test_size}')
    print(f'\n#{n_iter} 테스트 세트 인덱스 : {test_idx}')

print('\n Mean Accuracy : ', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#1 테스트 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#2 테스트 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#3 테스트 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#4 테스트 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#5 테스트 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 Mean Accuracy :  0.9


In [9]:
from sklearn.model_selection import StratifiedKFold

dt_clf = DecisionTreeClassifier(random_state=156)

kfold = StratifiedKFold(n_splits=5)
cv_accuracy = []

n_iter = 0

# KFold 객체의 split()을 호출하면 폴드 별 학습용, 테스트용 데이터의 인덱스를 array로 반환
for traind_idx, test_idx in kfold.split(features, label):
    X_train, X_test = features[traind_idx], features[test_idx]
    y_train, y_test = label[traind_idx], label[test_idx]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(y_test, pred), 4)
    cv_accuracy.append(accuracy)

    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(f'\n#{n_iter} 교차 검증 정확도 : {accuracy}, 학습 데이터 크기 : {train_size}, 테스트 데이터 크기 : {test_size}')
    print(f'\n#{n_iter} 테스트 세트 인덱스 : {test_idx}')

print('\n Mean Accuracy : ', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#1 테스트 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#2 테스트 세트 인덱스 : [ 10  11  12  13  14  15  16  17  18  19  60  61  62  63  64  65  66  67
  68  69 110 111 112 113 114 115 116 117 118 119]

#3 교차 검증 정확도 : 0.9, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#3 테스트 세트 인덱스 : [ 20  21  22  23  24  25  26  27  28  29  70  71  72  73  74  75  76  77
  78  79 120 121 122 123 124 125 126 127 128 129]

#4 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#4 테스트 세트 인덱스 : [ 30  31  32  33  34  35  36  37  38  39  80  81  82  83  84  85  86  87
  88  89 130 131 132 133 134 135 136 137 138 139]

#5 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 테스트 데이터 크기 : 30

#5 테스트 세트 인덱스 : [ 40  41  42  43  44  45  46  47  48  49  90  91  92  93  94  95  96  97
  98  99 140 141 142 143 144 145 146 147 148 149]

 Mean Accuracy :  0.

- StratifiedKFold 사용으로 정확도 상승

## cross_val_score()
- 분류 문제에선 내부적으로 StratifiedKFold 사용, 회귀문제에선 KFold사용

In [10]:
from sklearn.model_selection import cross_val_score

dt_clf = DecisionTreeClassifier(random_state=156)

scores = cross_val_score(estimator=dt_clf, X=features, y=label, scoring='accuracy', cv=3) # scoring에 지정된 성능 지표 측정값을 배열 형태로 반환
print(np.round(scores, 4))
print(np.round(np.mean(scores), 4))

[0.98 0.94 0.98]
0.9667


In [12]:
from sklearn.model_selection import cross_validate

scores = cross_validate(estimator=dt_clf, X=features, y=label, scoring='accuracy', cv=3, return_train_score=True)
scores

{'fit_time': array([0.00199652, 0.00099635, 0.00099802]),
 'score_time': array([0.       , 0.0009973, 0.       ]),
 'test_score': array([0.98, 0.94, 0.98]),
 'train_score': array([1., 1., 1.])}

In [13]:
print(np.round(scores['test_score'], 4))
print(np.round(np.mean(scores['test_score']), 4))

[0.98 0.94 0.98]
0.9667


## GridSearchCV - 하이퍼 파라미터 튜닝

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=121)

grid_parameters = {
    'max_depth': [1, 2, 3],
    'min_samples_split': [2, 3]
}

dtree = DecisionTreeClassifier(random_state=42)
grid_tree = GridSearchCV(estimator=dtree, param_grid=grid_parameters, cv=3, refit=True) # refit은 best parameter로 모델을 재학습시킴
grid_tree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [25]:
import pandas as pd

scores_df = pd.DataFrame(grid_tree.cv_results_)
scores_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.002326      0.000940         0.000997        0.000001   
1       0.002995      0.001412         0.001003        0.000021   
2       0.000996      0.000030         0.000998        0.000001   
3       0.000984      0.000020         0.000665        0.000471   
4       0.000999      0.000031         0.001000        0.000817   
5       0.001327      0.000466         0.000333        0.000471   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [26]:
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [27]:
grid_tree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [28]:
grid_tree.best_score_

0.975

In [29]:
estimator = grid_tree.best_estimator_
estimator

DecisionTreeClassifier(max_depth=3, random_state=42)

In [30]:
pred = estimator.predict(X_test)
accuracy_score(y_test, pred)

0.9666666666666667

## 인코딩
- LabelEncoder는 선형회귀에 사용시 주의. 트리 계열에는 큰 문제 없음

In [31]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [33]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [32]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

## One-Hot Encoding
- 원핫 인코더 변환 전, 숫자형 값으로 입력
- 입력 값으로 2차원 데이터 필요

In [34]:
from sklearn.preprocessing import OneHotEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels # array

array([0, 1, 4, 5, 3, 3, 2, 2])

In [38]:
# 2차원으로 변환
labels = labels.reshape((-1, 1))
print(labels.shape)
labels

(8, 1)


array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [39]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [41]:
print(oh_labels.shape)
oh_labels.toarray()

(8, 6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

- get_dummies()

In [46]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
df = pd.DataFrame(items).rename(columns={0: 'item'})
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [47]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0     True     False    False     False       False     False
1    False      True    False     False       False     False
2    False     False    False     False        True     False
3    False     False    False     False       False      True
4    False     False    False      True       False     False
5    False     False    False      True       False     False
6    False     False     True     False       False     False
7    False     False     True     False       False     False