In [1]:
import numpy as np

# array

## array의 차원

In [2]:
array1 = np.array([1, 2, 3])

print('Type : ', type(array1))
print('Shape : ', array1.shape)

Type :  <class 'numpy.ndarray'>
Shape :  (3,)


In [6]:
array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])

print('Type : ', type(array2))
print('Shape : ', array2.shape)

Type :  <class 'numpy.ndarray'>
Shape :  (2, 3)


In [7]:
array3 = np.array([[1, 2, 3]])

print('Type : ', type(array3))
print('Shape : ', array3.shape)

Type :  <class 'numpy.ndarray'>
Shape :  (1, 3)


In [9]:
print(f'array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')

array1: 1차원, array2: 2차원, array3: 2차원


## array의 데이터 타입

In [10]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [12]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)


['1' '2' 'test'] <U11
[1. 2. 3.] float64


## array 생성

In [13]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [15]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## reshape() : 차원변경

In [16]:
array1 = np.arange(10)
print('array1 :\n', array1)

array2 = array1.reshape(2, 5)
print('array2 :\n', array2)

array3 = array1.reshape(5, 2)
print('array3 :\n', array3)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape : ', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape :  (2, 5)
array3 shape :  (5, 2)


In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())
print('array3d shape:\n', array3d.shape)

# 3차원을 2차원으로
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:\n', array5.shape)

# 1차원을 2차원으로
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:\n', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d shape:
 (2, 2, 2)
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:
 (8, 1)


## 인덱싱

In [27]:
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
value = array1[2]
value, type(value)

(3, numpy.int32)

In [31]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array2d[0, 0], array2d[0, 1], array2d[1, 0], array2d[2, 2]

(1, 2, 4, 9)

In [33]:
array1 = np.arange(1, 10)
array4 = array1[:3]
array5 = array1[3:]
array6 = array1[:]

print(array4)
print(array5)
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
array4 = array2d[[0, 1], :2]
array5 = array2d[[0, 1]]

print(array2d)
print(array3)
print(array4)
print(array5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [39]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [40]:
array3 = array1d[array1d > 5]
array3

array([6, 7, 8, 9])

In [41]:
org_array = np.array([3, 1, 9, 5])
org_array

array([3, 1, 9, 5])

## 정렬
- np.sort()
- ndarray.sort()

In [43]:
sort_array1 = np.sort(org_array)
print('원본', org_array)
print('정렬', sort_array1)

원본 [3 1 9 5]
원본 [1 3 5 9]


In [44]:
sort_array2 = org_array.sort() #반환값 없음, 원본 행렬 변경
print('원본', org_array)
print('정렬', sort_array2)

원본 [1 3 5 9]
정렬 None


In [46]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
sort_array1_desc

array([9, 5, 3, 1])

In [48]:
array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
sort_array2d_axis1 = np.sort(array2d, axis=1)

print(array2d)
print(sort_array2d_axis0)
print(sort_array2d_axis1)


[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


- np.argsort()

In [49]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [51]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 이름 출력 : ', name_array[sort_indices_asc])
sort_indices_desc = np.argsort(score_array)[::-1]
print('성적 내림차순 이름 출력 : ', name_array[sort_indices_desc])

성적 오름차순 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
성적 내림차순 이름 출력 :  ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


# 행렬

- 행렬 내적

In [52]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
dot_product = np.dot(A, B)
print('행렬 내적 : \n', dot_product)

행렬 내적 : 
 [[ 58  64]
 [139 154]]


- 행렬 전치

In [53]:
A = np.array([
    [1, 2],
    [3, 4]
])

A_transpose = np.transpose(A)
A_transpose

array([[1, 3],
       [2, 4]])